
-- ============================================================
-- AMUC - MÓDULO SEGURIDAD V17
-- Ejecutar en Supabase PRODUCCIÓN.
-- ============================================================

-- Tablas (por si todavía no fueron creadas)
create table if not exists public.reserva_seguridad (
  id bigint generated by default as identity primary key,
  reserva_id bigint not null references public.reservas(id) on delete cascade,
  ingreso_real timestamptz,
  ingreso_usuario_id uuid references auth.users(id),
  egreso_real timestamptz,
  egreso_usuario_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reserva_seguridad_reserva_unique unique (reserva_id)
);

create table if not exists public.reserva_observaciones (
  id bigint generated by default as identity primary key,
  reserva_id bigint not null references public.reservas(id) on delete cascade,
  usuario_id uuid not null references auth.users(id),
  observacion text not null,
  created_at timestamptz not null default now()
);

alter table public.reserva_seguridad enable row level security;
alter table public.reserva_observaciones enable row level security;

-- ------------------------------------------------------------
-- Función auxiliar: usuario autorizado para panel de Seguridad
-- ------------------------------------------------------------
create or replace function public.es_usuario_seguridad_autorizado()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.perfiles p
    where p.id = auth.uid()
      and p.activo = true
      and p.rol in ('SEGURIDAD','ADMINISTRADOR','ADMINISTRACION')
  );
$$;

revoke all on function public.es_usuario_seguridad_autorizado() from public;
grant execute on function public.es_usuario_seguridad_autorizado() to authenticated;

-- ------------------------------------------------------------
-- Eventos visibles en Seguridad: sólo datos operativos.
-- No devuelve valores, cobros ni datos de facturación.
-- ------------------------------------------------------------
create or replace function public.get_seguridad_eventos(
  p_desde date,
  p_hasta date
)
returns table (
  id bigint,
  fecha date,
  hora_inicio time,
  hora_fin time,
  tipo_evento text,
  cantidad_personas integer,
  estado text,
  cliente_nombre text,
  cliente_apellido text,
  telefono text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.es_usuario_seguridad_autorizado() then
    raise exception 'USUARIO_NO_AUTORIZADO';
  end if;

  return query
  select
    r.id,
    r.fecha,
    r.hora_inicio,
    r.hora_fin,
    r.tipo_evento,
    r.cantidad_personas,
    r.estado,
    c.nombre,
    c.apellido,
    c.telefono
  from public.reservas r
  left join public.clientes c on c.id = r.cliente_id
  where r.fecha between p_desde and p_hasta
    and coalesce(r.estado,'') <> 'CANCELADA'
  order by r.fecha, r.hora_inicio;
end;
$$;

revoke all on function public.get_seguridad_eventos(date,date) from public;
grant execute on function public.get_seguridad_eventos(date,date) to authenticated;

-- ------------------------------------------------------------
-- Observaciones con nombre del usuario que las registró
-- ------------------------------------------------------------
create or replace function public.get_reserva_observaciones_seguridad(
  p_reserva_id bigint
)
returns table (
  id bigint,
  observacion text,
  created_at timestamptz,
  usuario_id uuid,
  usuario_nombre text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.es_usuario_seguridad_autorizado() then
    raise exception 'USUARIO_NO_AUTORIZADO';
  end if;

  return query
  select
    o.id,
    o.observacion,
    o.created_at,
    o.usuario_id,
    trim(concat_ws(' ',p.nombre,p.apellido))
  from public.reserva_observaciones o
  left join public.perfiles p on p.id = o.usuario_id
  where o.reserva_id = p_reserva_id
  order by o.created_at desc;
end;
$$;

revoke all on function public.get_reserva_observaciones_seguridad(bigint) from public;
grant execute on function public.get_reserva_observaciones_seguridad(bigint) to authenticated;

-- ------------------------------------------------------------
-- Registro de ingreso/egreso con nombre del usuario
-- ------------------------------------------------------------
create or replace function public.get_seguridad_registro(
  p_reserva_id bigint
)
returns table (
  ingreso_real timestamptz,
  egreso_real timestamptz,
  ingreso_usuario_nombre text,
  egreso_usuario_nombre text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.es_usuario_seguridad_autorizado() then
    raise exception 'USUARIO_NO_AUTORIZADO';
  end if;

  return query
  select
    s.ingreso_real,
    s.egreso_real,
    trim(concat_ws(' ',pi.nombre,pi.apellido)),
    trim(concat_ws(' ',pe.nombre,pe.apellido))
  from public.reserva_seguridad s
  left join public.perfiles pi on pi.id = s.ingreso_usuario_id
  left join public.perfiles pe on pe.id = s.egreso_usuario_id
  where s.reserva_id = p_reserva_id
  limit 1;
end;
$$;

revoke all on function public.get_seguridad_registro(bigint) from public;
grant execute on function public.get_seguridad_registro(bigint) to authenticated;

-- ------------------------------------------------------------
-- Registrar ingreso / egreso. Fecha, hora y usuario automáticos.
-- ------------------------------------------------------------
create or replace function public.registrar_movimiento_seguridad(
  p_reserva_id bigint,
  p_tipo text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_tipo text := upper(trim(p_tipo));
begin
  if not public.es_usuario_seguridad_autorizado() then
    raise exception 'USUARIO_NO_AUTORIZADO';
  end if;

  if v_tipo not in ('INGRESO','EGRESO') then
    raise exception 'TIPO_MOVIMIENTO_INVALIDO';
  end if;

  insert into public.reserva_seguridad(reserva_id)
  values (p_reserva_id)
  on conflict (reserva_id) do nothing;

  if v_tipo='INGRESO' then
    update public.reserva_seguridad
    set ingreso_real = coalesce(ingreso_real,now()),
        ingreso_usuario_id = case when ingreso_real is null then auth.uid() else ingreso_usuario_id end,
        updated_at = now()
    where reserva_id = p_reserva_id;
  else
    update public.reserva_seguridad
    set egreso_real = coalesce(egreso_real,now()),
        egreso_usuario_id = case when egreso_real is null then auth.uid() else egreso_usuario_id end,
        updated_at = now()
    where reserva_id = p_reserva_id;
  end if;
end;
$$;

revoke all on function public.registrar_movimiento_seguridad(bigint,text) from public;
grant execute on function public.registrar_movimiento_seguridad(bigint,text) to authenticated;

-- ------------------------------------------------------------
-- La lista de invitados es el único adjunto visible para Seguridad.
-- ------------------------------------------------------------
create or replace function public.get_lista_invitados_seguridad(
  p_reserva_id bigint
)
returns table (
  nombre_archivo text,
  ruta_storage text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.es_usuario_seguridad_autorizado() then
    raise exception 'USUARIO_NO_AUTORIZADO';
  end if;

  return query
  select
    d.nombre_archivo,
    d.ruta_storage,
    d.updated_at
  from public.reserva_documentos d
  where d.reserva_id = p_reserva_id
    and d.tipo_documento = 'LISTA_INVITADOS'
  limit 1;
end;
$$;

revoke all on function public.get_lista_invitados_seguridad(bigint) from public;
grant execute on function public.get_lista_invitados_seguridad(bigint) to authenticated;

-- ------------------------------------------------------------
-- Observaciones: lectura e inserción.
-- No hay UPDATE ni DELETE para SEGURIDAD.
-- ------------------------------------------------------------
drop policy if exists "Roles autorizados leen observaciones" on public.reserva_observaciones;
create policy "Roles autorizados leen observaciones"
on public.reserva_observaciones
for select
to authenticated
using (public.es_usuario_seguridad_autorizado());

drop policy if exists "Seguridad registra observaciones" on public.reserva_observaciones;
create policy "Seguridad registra observaciones"
on public.reserva_observaciones
for insert
to authenticated
with check (
  usuario_id = auth.uid()
  and public.es_usuario_seguridad_autorizado()
);

-- ------------------------------------------------------------
-- Registro operativo: lectura/escritura sólo a roles autorizados.
-- ------------------------------------------------------------
drop policy if exists "Roles autorizados leen seguridad" on public.reserva_seguridad;
create policy "Roles autorizados leen seguridad"
on public.reserva_seguridad
for select
to authenticated
using (public.es_usuario_seguridad_autorizado());

drop policy if exists "Seguridad crea registro operativo" on public.reserva_seguridad;
create policy "Seguridad crea registro operativo"
on public.reserva_seguridad
for insert
to authenticated
with check (public.es_usuario_seguridad_autorizado());

drop policy if exists "Seguridad actualiza registro operativo" on public.reserva_seguridad;
create policy "Seguridad actualiza registro operativo"
on public.reserva_seguridad
for update
to authenticated
using (public.es_usuario_seguridad_autorizado())
with check (public.es_usuario_seguridad_autorizado());

-- ------------------------------------------------------------
-- Storage: reemplaza la política amplia anterior.
-- Administración ve todos los documentos.
-- Seguridad sólo puede abrir lista_invitados.
-- ------------------------------------------------------------
drop policy if exists "Usuarios autenticados leen documentos reservas storage" on storage.objects;

drop policy if exists "AMUC lee documentos reservas storage" on storage.objects;
create policy "AMUC lee documentos reservas storage"
on storage.objects
for select
to authenticated
using (
  bucket_id='documentos-reservas'
  and (
    exists (
      select 1 from public.perfiles p
      where p.id=auth.uid()
        and p.activo=true
        and p.rol in ('ADMINISTRADOR','ADMINISTRACION')
    )
    or (
      exists (
        select 1 from public.perfiles p
        where p.id=auth.uid()
          and p.activo=true
          and p.rol='SEGURIDAD'
      )
      and name like '%/lista_invitados/%'
    )
  )
);

-- Índices
create index if not exists reserva_observaciones_reserva_idx
  on public.reserva_observaciones(reserva_id);

create index if not exists reserva_observaciones_usuario_idx
  on public.reserva_observaciones(usuario_id);

create index if not exists reserva_observaciones_fecha_idx
  on public.reserva_observaciones(created_at);
